name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version (e.g., 1.0.0, latest, dev)'
        required: true
        default: 'latest'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo
        run: echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:${{ github.event.inputs.version }}
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ github.event.inputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            API_KEY=${{ secrets.API_KEY }}